/*global window*/
window.Teavents = {
    MESSAGE: "message",
    VISIBILITY_HIDDEN: "visibility:hidden",
    VISIBILITY_VISIBLE: "visibility:visible",
    VISIBILITY_CHANGE: "visibilitychange",
    FULLSCREEN_ENTER: "fullscreen:enter",
    FULLSCREEN_EXIT: "fullscreen:exit",
    SCROLL_TOP: "scroll:top",
    FREEZE_BODY: "body:freeze",
    UNFREEZE_BODY: "body:unfreeze",
    OPTIONS_CLOSED: "options:closed",
    EPUB_SEND: "sendEpub",
    READY_TO_READ: "readyToRead",
    SEND_RESOURCES: "sendResources",
    TOC: "toc",
    WORKING: "working",
    NOT_WORKING: "not-working",
    PAGE_BOOKMARKED: "page-bookmarked",
    CURRENT_POSITION: "current-position",
    SCAN_FINISHED: "scan-finished",

    Readium: {
        PAGINATION_CHANGED: "PaginationChanged",
        CONTENT_LOAD_START: "ContentDocumentLoadStart",
        CONTENT_LOADED: "ContentDocumentLoaded",
        SETTINGS_APPLIED: "SettingsApplied",
        GESTURE_TAP: "GestureTap",
        GESTURE_PINCH_MOVE: "GesturePinchMove",
        GESTURE_PINCH: "GesturePinch"
    },

    Actions: {
        BOOKMARK_PAGE: "bookmark-page",
        GET_POSITION: "get-position",
        LOG: "log",
        OPEN_EPUB: "open-epub",
        OPEN_CHAPTER: "open-chapter",
        OPEN_PAGE: "open-page",
        OPEN_POSITION: "open-position",
        SET_FONT_SIZE: "font-size",
        SET_THEME: "set-theme"
    },

    Events: {
        START_APP: "start-app",
        OPEN_APP: "open-app",
        CLOSE_APP: "close-app",
        EMPTY_BOOKCASE: "bookcase-empty",
        OPEN_BOOK: "open-book",
        CLOSE_BOOK: "close-book",
        ADD_BOOK: "add-book",
        DELETE_BOOK: "delete-book",
        BOOKMARK_PAGE: "bookmark-page",
        CLICK_TOC_ITEM: "click-toc-item",
        SEARCH: "search",
        SHOW_BOOKMARKS: "show-bookmarks",
        SHOW_OPTIONS: "show-options",
        SHOW_TOC: "show-toc",
        CHANGE_FONT_SIZE: "change-font-size",
        CHANGE_ORIENTATION: "orientation-change",
        CHANGE_SETTING_VIEW: "change-setting-view",
        CHANGE_SETTING_ORDER: "change-setting-order",
        CHANGE_THEME: "change-theme",
        PAGE_CHANGED: "pagination-changed",
        SETTINGS_CHANGED: "settings-changed",
        PINCH: "pinch",
        TAP: "tap",
        NO_CONNECTION: "no-connection",
        OPEN_SETTINGS: "open-settings"
    }
};